### ISSUE TITLE
KeyError:TFDS_DATA_DIR

### ISSUE THREAD

**Issue by CodeGod-zorebug** [FederatedML/FedCompress#1]
Hi, taking a moment of your time to ask a code question. If I run the code with python run.py --datasets cifar10 --method fedavg command there is no problem, but when I run the code with python run.py --datasets cifar10 --method fedcompress command it says KeyError:TFDS_DATA_DIR, please tell me what is the reason for this error. Thank you very much!

**Comment by CodeGod-zorebug** [comment]
Could you please tell me what the stylegan_oriented file in your code is?

**Comment by vtsouval** [comment]
Hi @CodeGod-zorebug,

You need to set `TFDS_DATA_DIR` environmental variable to point to the TensorFlow datasets directory.  You can download and prepare the StyleGan (oriented) dataset the from [here](https://github.com/mbaradad/learning_with_noise/tree/main/generate_datasets).
